add_newline = true

format = """\
  $username\
  $directory\
  $git_branch\
  $git_commit\
  $git_state\
  $line_break\
  $character\
  """

[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"

[cmd_duration]
min_time = 500
format = "took [$duration]($style) "

[directory]
truncation_length = 3
truncate_to_repo = false
disabled = false

[hostname]
ssh_only = false
format = "[$hostname]($style) in "
trim_at = "."
disabled = false

[line_break]
disabled = false

[username]
style_root = "bold red"
style_user = "bold yellow"
show_always = false
disabled = false

[git_branch]
format="on [$branch]($style) "
style="bold yellow" 
